language: ruby
rvm:
    - 2.5.3

script:
    - bundle exec jekyll build
    - bundle exec htmlproofer _site/ --assume_extension --http_status_ignore "0,999"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler
sudo: false
