######################################################
############## DO NOT TOUCH THIS PART ################
######################################################
sass:
  sass_dir: assets/css
  style: nested

include:
  - _pages

page_gen:
  - data: "members"
    template: "people"
    name: "flatname"
    dir: ""
    filter_condition: "record['lang'] == 'fr'"
  - data: "members"
    template: "people"
    name: "flatname"
    dir: "en/"
    filter_condition: "record['lang'] == 'en'"
  - data: "courses"
    template: course
    name: "course_id"
    dir: "cours/"
    filter_condition: "record['lang'] == 'fr'"
  - data: "courses"
    template: course
    name: "course_id"
    dir: "en/course/"
    filter_condition: "record['lang'] == 'en'"

img_path: "/assets/img/"

markdown: kramdown

excerpt_separator: <!--more-->

######################################################
######################################################
# General settings

title: REhPERE

subtitle: Réseau en Épistémologie et en Histoire de la Pensée Économique Récente

# Bibliography
scholar:
  bibliography_list_tag: "ul"
  bibliography_class: "fa-ul"
  sort_by: year
  order: descending
  bibliography_template: bib
  group_by: year
  group_order: descending
  bibliography_group_tag: 'h4 class="text-muted"'

twitter-timeline:
  link: "https://twitter.com/rehpere"
  number-of-tweets: "6"

index:
  fr:
  en: home.html

# Header
menu:
  fr:
    home:
      name: "Accueil"
      url: "/"
      prep: '<i class="fas fa-home"></i>'
    master:
      name: "Master ESH"
      prep: '<i class="fas fa-user-graduate"></i>'
      url: "/master/"
      sublinks:
        - name: "Présentation"
          url: "/master/#presentation"
        - name: "Mémoire"
          url: "/master/#memoire"
        - name: "Débouchées"
          url: "/master/#debouches"
      secondary-sublinks:
        - name: "Cours"
          url: "/cours"
    team:
      name: "Membres"
      url: "/membres/"
      prep: '<i class="fas fa-users"></i>'
    publications:
      name: "Publications"
      url: "/publications/"
      prep: '<i class="fas fa-book"></i>'
    blog:
      name: "Actualités"
      url: "/actualites/"
      prep: '<i class="fas fa-newspaper"></i>'
    research:
      name: "Réseau"
      url: "/reseau/"
      prep: '<i class="fas fa-globe-africa"></i>'
  en:
    home:
      name: "Home"
      url: "/home.html"
      prep: '<i class="fas fa-home"></i>'
    master:
      name: "Master ESH"
      url: "/en/master"
      prep: '<i class="fas fa-user-graduate"></i>'
    team:
      name: "Members"
      url: "/en/members"
      prep: '<i class="fas fa-users"></i>'
    publications:
      name: "Publications"
      url: "/en/publications"
      prep: '<i class="fas fa-book"></i>'
    blog:
      name: "News"
      url: "/en/news"
      prep: '<i class="fas fa-newspaper"></i>'
    research:
      name: "Network"
      url: "/en/network"
      prep: '<i class="fas fa-globe-africa"></i>'

####### Home ########
home:
  fr:
    anchored-info: "Publication ancrée"
  en:
    anchored-info: "Anchored publication"

####### Team ########
team:
  fr:
    title: "L'équipe"
  en:
    title: "The team"

####### Publications ########
biblio:
  fr:
    title: "Dernières publications"
  en:
    title: "Latest publications"

####### blog ########
more:
  fr: "Lire la suite"
  en: "Read more"

####### Personal page ######
people:
  fr:
    about: "À propos"
    externals: "Liens externes"
    publications: "Publications"
  en:
    about: "About"
    externals: "External links"
    publications: "Publications"
####### Courses ########
courses:
  fr:
    title: "Enseignements"
    semester: "Semestre"
  en:
    title: "Courses"
    semester: "Semester"

###### footer ######
logos:
  - "CES.png"
  - "paris1.png"
  - "cnrs.png"
